services:
  kafka:
    image: apache/kafka:3.7.2
    ports:
      - "9092:9092"
    environment:
      # "connection string"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      # Single node "cluster" overrides. Docs @ https://hub.docker.com/r/apache/kafka
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092,CONTROLLER://localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
  sandbox:
    image: golang:1.23
    volumes:
      - ..:/workspace:cached
    working_dir: /workspace
    # Hack. We need a process running indefinitely so we can attach a tty to its container
    command: sleep infinity
    environment:
      # Used by our binaries
      CONN_STRING: kafka:9092
      # Used by the sarama helper binaries
      KAFKA_PEERS: kafka:9092
    depends_on:
      - kafka
